version: "3.4"

services:
  reverse-proxy:
    image: traefik:v1.7.8
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - traefik-net
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/acme.json:/acme.json
    configs:
      - source: traefik-config
        target: /etc/traefik/traefik.toml
      - source: traefik-rules
        target: /etc/traefik/rules.toml
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.domain=${MAIN_DOMAIN}"
        - "traefik.docker.network=traefik"
        - "traefik.backend=traefik"
        - "traefik.port=8080"
        - "traefik.frontend.auth.basic=${AUTH_TRAEFIK_USER}:${AUTH_TRAEFIK_PASSWORD}"
        - "traefik.frontend.rule=Host:traefik.${MAIN_DOMAIN}"
        - "traefik.entrypoints=https"
        - "traefik.frontend.passHostHeader=true"

networks:
  traefik-net:
    driver: overlay
  traefik:
    driver: overlay
    external: true

configs:
  traefik-config:
    file: ./config/traefik.toml
  traefik-rules:
    file: ./config/rules.toml
